### ISSUE TITLE
Build with Docker for Linux

### ISSUE THREAD

**Issue by ararslan** [ararslan/fftw-builder#2]
Gives a more controlled environment for making redistributable binaries. The image should be `staticfloat/julia_workerbase:centos6_9-x64` (s/x64/x86 for 32-bit Linux). We should also use Docker for MinGW cross-compilation for Windows but I don't know what image to use for that.

**Comment by ararslan** [comment]
@tkelman and @staticfloat, any good recommendations for an existing image for MinGW cross compilation that will be compatible with our Windows Julia binaries? (Or if not, any tips on how to set one up?)

**Comment by ararslan** [comment]
To paraphrase Tony in a discussion elsewhere, for Windows we just need a Docker image with a mingw-w64 gcc that's ABI compatible with how Cygwin builds theirs, things like `--enable-fully-dynamic-string`, threading, and exception model variants, and whether they're using C++11 ABI or an old one.

**Comment by ararslan** [comment]
@tkelman If I recall correctly, you said offline that AppVeyor should now be able to build Julia-compatible binaries. Is that true? Could AV be used for Windows binaries here after all rather than trying to find or build a suitable Docker image?

**Comment by tkelman** [comment]
It's not a good idea for anything more than a handful of files, it's going to be really slow.

**Comment by ararslan** [comment]
Not sure what you mean. I don't care how long it takes since it's building on CI.

**Comment by tkelman** [comment]
For a library as large as FFTW, it could time out appveyor.

**Comment by ararslan** [comment]
It's _that_ slow?? It's only about 5 minutes on Travis. Well do let me know if you have Docker suggestions because I'm not even sure what to look for.

**Comment by ararslan** [comment]
Looks like AV is going to work after all.
