### ISSUE TITLE
No one uploads their binaries to releases

### ISSUE THREAD

**Issue by ararslan** [ararslan/fftw-builder#7]
I created a test release to see whether my deployment setup for Travis and Circle is correct (I haven't set up AV's deployment yet). From the Travis log:
```
Skipping a deployment with the releases provider because this is not a tagged commit
```
I guess I need to use Git tags rather than GitHub releases? I was under the impression that the latter created tags...

Similarly, it appears a tag build for Circle wasn't triggered at all. :/

**Comment by ararslan** [comment]
Any experience with uploading to releases, @tkelman? I think I'm just going to do build artifacts with Circle and AppVeyor then download them manually, but Travis doesn't store artifacts for you, you can only upload them to AWS.

**Comment by tkelman** [comment]
has worked for me in the past https://github.com/tkelman/docker-containers-build/blob/ef19ff0a79a650fc5b7549da63b9ae2128dd6572/.travis.yml#L32-L39

**Comment by ararslan** [comment]
Hm, maybe my setup is wrong then. Did creating a release in the GitHub UI trigger that for you, or did you have to create a tag instead?

**Comment by tkelman** [comment]
My understanding matches yours that the former should trigger the latter. See a few lines above, it was tagging and pushing.

**Comment by ararslan** [comment]
Hm, I still can't seem to get Travis to upload to the release. Tagging a release actually doesn't even seem to be triggering any of the CI systems. :/

Tony, in the setup you linked, you're pushing a new tag from Travis? How would that work with multiple OSes running on Travis like I'm doing here? Since this is turning out to be such a pain, do you know of a way in which I can just get the raw build artifacts from Travis easily? I guess I could upload the tarball as a GitHub Gist, but that seems almost perverse...

**Comment by ararslan** [comment]
```
travis_time:end:00849150:start=1502756326040979174,finish=1502756326070597486,duration=29618312
[0Ktravis_fold:end:before_deploy
[0Ktravis_fold:start:dpl.0
[0Ktravis_time:start:015739b0
[0KSuccessfully installed dpl-1.8.40
1 gem installed

travis_time:end:015739b0:start=1502756326078175597,finish=1502756327179441636,duration=1101266039
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:365d221a
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.12.2
Successfully installed public_suffix-2.0.5
Successfully installed addressable-2.5.1
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.6.2
6 gems installed
Successfully installed mime-types-2.99.3
1 gem installed

travis_fold:end:dpl.1
Logged in as Alex Arslan
Deploying to repo: ararslan/fftw-builder
Current tag is: v3.3.6-pl2
travis_fold:start:dpl.2
[33mPreparing deploy[0m

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m

travis_fold:end:dpl.3

travis_time:end:365d221a:start=1502756327187124028,finish=1502756329803876635,duration=2616752607
[0K
Done. Your build exited with 0.
```
But the binaries don't seem to be anywhere...?

**Comment by tkelman** [comment]
Open an issue with travis?

**Comment by ararslan** [comment]
I'm not certain it isn't user error. Is the expected workflow the following?

1. Tag a release using the GitHub releases UI
2. Travis runs on the tag commit
3. Travis edits the release that triggered the tag build to include the built artifacts

That's what I was expecting, but maybe that isn't right.

**Comment by ararslan** [comment]
Resolved. :)
